language: generic

sudo: require

services:
  - docker

before_install:
  - docker build -t abenson91/docker-react -f Dockerfile-dev .

script:
  - docker run -e CI=true abenson91/docker-react npm run test